### ISSUE TITLE
Authentification now required for MODIs downloads

### ISSUE THREAD

**Issue by NPounder** [multiply-org/grabba_grabba_hey#5]
LPDAAC now require login credentials to download MODIS data. See [https://lpdaac.usgs.gov/data_access/data_pool](https://lpdaac.usgs.gov/data_access/data_pool) 

> "As of July 20, 2016, users are now required to log in with their Earthdata login credentials to obtain data. When accessing data via the Data Pool direct access links, you will now be prompted to enter your credentials. Script users should modify their code to reflect this change. For examples please see the Command Line Tips document."

Now modis_downloader returns files with just an error inside:  `HTTP Basic: Access denied.`

I will put a fix together and submit a pull request

**Comment by jgomezdans** [comment]
071dee4ea088fe60775952983404b85cd455a9cb closes this, it seems to work OK now....
